name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  build_test_image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build Test Image
        run: |
          docker build -t ${{ github.event.before }} -f ./Dockerfile.staging .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ github.event.before }}
          docker system prune -f

  deploy_test:
    runs-on: ubuntu-latest
    needs: build_test_image
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy Test
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "docker pull ${{ github.event.before }}"
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "docker stop ${{ github.event.before }} || true"
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "docker rm ${{ github.event.before }} || true"
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "docker run -d --name ${{ github.event.before }} -p 8080:8080 ${{ github.event.before }}"